### ISSUE TITLE
[BUG] Panic when checking the version in Linux

### ISSUE THREAD

**Issue by thenexxuz** [gitkraken/gk-cli#29]
### Description

Env: Linux

Command: `gk version`

Error:
```
panic: interface conversion: interface {} is nil, not version.NewVersionInfo

goroutine 1 [running]:
github.com/gitkraken/cli/pkg/cmd.endVersionCheck(0x254aff8?, {0x252b690, 0xc0001ccbd0}, {0x2526c40, 0xc000070038}, 0x40?)
        /Users/runner/work/cli/cli/pkg/cmd/root_command.go:139 +0x11a
github.com/gitkraken/cli/pkg/cmd.NewCmdRoot.func2(0xc00062e300?, {0x1592f34?, 0x4?, 0x1592ef0?})
        /Users/runner/work/cli/cli/pkg/cmd/root_command.go:56 +0x69
github.com/spf13/cobra.(*Command).execute(0xc00062e300, {0x314a480, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:936 +0xa22
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006cd200)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(0x2526050?, {0x2531388?, 0x314a480?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961 +0x47
main.main()
        /Users/runner/work/cli/cli/cmd/gk/main.go:30 +0x12e
```

![image](https://github.com/gitkraken/gk-cli/assets/97260773/d9682f4e-694f-4eba-940a-c4e78e9869de)

### GitKraken CLI Version

1.2.0

### OS Version

EndeavourOS Linux

### Git Version

2.43.0

**Comment by thenexxuz** [comment]
Seemed that this was a false positive... I ran the version command within the same terminal after updating but after restarting my terminal, the error has gone away.

**Comment by sergiolms** [comment]
Hi @thenexxuz,
Glad to hear you solved the issue. I spotted why this message may be appearing, so I'll address this to avoid it in the future.
