### ISSUE TITLE
[BUG] `gk focus` panic in local workspace

### ISSUE THREAD

**Issue by Elkiwa** [gitkraken/gk-cli#31]
### Description

1. Having a default local workspace with 2 repos,  I added Github as a provider
2. Use `gk focus` command

```PowerShell
PS D:\dev\Elkiwa\Main> gk settings
- Default workspace: ScoopInstaller
- Max display items: 30
- Max concurrency: 3
- Clone protocol: ssh
- Open default:
```

### GitKraken CLI Version

1.2.2

### OS Version

- OS: Windows 11
- Version: 23H2 22631.2715
- Arch: x86_64

### Git Version

git version 2.43.0.windows.1

### Logs, Screenshots, Screen Captures, URLs, etc

```PowerShell
PS D:\dev\Elkiwa\Main> gk focus
Using default workspace: ScoopInstaller
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x18cb134]

goroutine 1 [running]:
github.com/gitkraken/cli/pkg/infrastructure/domain.UserRestRepository.GetProviderUserInfo({{_, _}, {_, _}, {_, _}, {_, _}}, {{0xc000031050, 0x24}, ...}, ...)
        /Users/runner/work/cli/cli/pkg/infrastructure/domain/user_rest_repository.go:94 +0xf4
github.com/gitkraken/cli/pkg/cmd/focus.NewCmdFocus.func2(0xc000144000, {0x1b7115b?, 0x4?, 0x1b71083?})
        /Users/runner/work/cli/cli/pkg/cmd/focus/focus.go:69 +0x448
github.com/spf13/cobra.(*Command).execute(0xc000144000, {0x375c5e0, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000145500)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(0xc000122db0?, {0x2b0df88?, 0x375c5e0?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961 +0x47
main.main()
        /Users/runner/work/cli/cli/cmd/gk/main.go:55 +0x63a
```

**Comment by Elkiwa** [comment]
Confirmed the issue has been resolved in version `1.3.0`
