### ISSUE TITLE
[BUG] Errors when using commands that require interacting with Bitbucket Server

### ISSUE THREAD

**Issue by stevensnicholas** [gitkraken/gk-cli#56]
### Description

A go error happens when trying to ls pr from bitbucket server 

### GitKraken CLI Version

2.01

### OS Version

windows 10

### Git Version

git version 2.36.1.windows.1

### Logs, Screenshots, Screen Captures, URLs, etc

PS C:\xxxx\gir_repo>gk pr view
Workspace: Data Engineering
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0x142f30b]

goroutine 77 [running]:
github.com/gitkraken/cli/pkg/infrastructure/domain.PullRequestRestRepository.listFromRepos.func1.1(0x1, {{0x0, 0x0}, {0x0, 0x0}, {0xc000784380, 0x20}, {0x0, 0x0}, {0xc0007ce473, ...}, ...})
        /Users/runner/work/cli/cli/pkg/infrastructure/domain/pull_request_rest_repository.go:174 +0x6ab
created by github.com/gitkraken/cli/pkg/infrastructure/domain.PullRequestRestRepository.listFromRepos.func1 in goroutine 8
        /Users/runner/work/cli/cli/pkg/infrastructure/domain/pull_request_rest_repository.go:146 +0x453

**Comment by JBUinfo** [comment]
Hi!
We will close all issues prior to March 28th as version 3.0.0 includes major changes. We appreciate your contribution and hope you will continue using the CLI

Thank you!
